# Generated by Django 6.0.3 on 2026-04-30 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('path', models.CharField(max_length=500, verbose_name='路径')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '预置数据集目录',
                'verbose_name_plural': '预置数据集目录',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据集名称')),
                ('source_path', models.CharField(help_text='包含COLMAP或Blender数据的目录路径', max_length=500, verbose_name='数据路径')),
                ('format_type', models.CharField(choices=[('colmap', 'COLMAP'), ('blender', 'Blender/NeRF')], default='colmap', max_length=20, verbose_name='数据格式')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '数据集',
                'verbose_name_plural': '数据集',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('status', models.CharField(choices=[('created', '已创建'), ('partitioning', '数据分区中'), ('training', '训练中'), ('completed', '训练完成'), ('rendering', '渲染中'), ('evaluating', '评估中'), ('evaluated', '已评估'), ('failed', '失败')], default='created', max_length=20, verbose_name='状态')),
                ('source_path', models.CharField(blank=True, max_length=500, verbose_name='数据源路径')),
                ('exp_name', models.CharField(blank=True, max_length=200, verbose_name='实验名称')),
                ('resolution', models.IntegerField(default=-1, help_text='-1=自动, 1=原始, 2=1/2, 4=1/4, 8=1/8', verbose_name='分辨率缩放')),
                ('eval_mode', models.BooleanField(default=False, verbose_name='评估模式')),
                ('llffhold', models.IntegerField(default=83, verbose_name='LLFF测试间隔')),
                ('white_background', models.BooleanField(default=False, verbose_name='白色背景')),
                ('sh_degree', models.IntegerField(default=3, verbose_name='SH度数')),
                ('data_device', models.CharField(default='cuda', max_length=10, verbose_name='数据设备')),
                ('manhattan', models.BooleanField(default=False, verbose_name='曼哈顿对齐')),
                ('platform', models.CharField(choices=[('cc', 'CloudCompare'), ('tj', 'Three.js')], default='cc', max_length=10, verbose_name='对齐平台')),
                ('pos', models.CharField(blank=True, default='', help_text='例如: "25.6 0.0 -12.0"', max_length=200, verbose_name='平移向量')),
                ('rot', models.CharField(blank=True, default='', help_text='cc:9个元素 tj:3个元素', max_length=500, verbose_name='旋转矩阵/向量')),
                ('m_region', models.IntegerField(default=3, verbose_name='X方向分区数')),
                ('n_region', models.IntegerField(default=3, verbose_name='Z方向分区数')),
                ('extend_rate', models.FloatField(default=0.2, verbose_name='边界扩展率')),
                ('visible_rate', models.FloatField(default=0.25, verbose_name='可见性比率')),
                ('iterations', models.IntegerField(default=30000, verbose_name='训练迭代数')),
                ('test_iterations', models.CharField(default='7_000 30_000 60_000', max_length=100, verbose_name='测试迭代点')),
                ('save_iterations', models.CharField(default='7_000 30_000 60_000', max_length=100, verbose_name='保存迭代点')),
                ('checkpoint', models.CharField(blank=True, max_length=500, null=True, verbose_name='检查点')),
                ('quiet', models.BooleanField(default=False, verbose_name='安静模式')),
                ('model_path', models.CharField(blank=True, max_length=500, verbose_name='模型输出路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.dataset', verbose_name='数据集')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('train', '训练'), ('render', '渲染'), ('eval', '评估'), ('convert', '格式转换'), ('merge', '无缝合并')], max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('command', models.TextField(blank=True, verbose_name='命令')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='进程ID')),
                ('log_file', models.CharField(blank=True, max_length=500, verbose_name='日志文件')),
                ('output', models.TextField(blank=True, default='', verbose_name='输出')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(default=60000, verbose_name='迭代次数')),
                ('psnr', models.FloatField(blank=True, null=True, verbose_name='PSNR')),
                ('ssim', models.FloatField(blank=True, null=True, verbose_name='SSIM')),
                ('lpips', models.FloatField(blank=True, null=True, verbose_name='LPIPS')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='原始数据')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
                ('eval_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.job', verbose_name='评估任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '评估结果',
                'verbose_name_plural': '评估结果',
            },
        ),
    ]
