# Generated by Django 5.2.9 on 2025-12-25 00:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconstructionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='3D重建任务', max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('resolution', models.IntegerField(default=1024, validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(4096)], verbose_name='重建分辨率')),
                ('iterations', models.IntegerField(default=30000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)], verbose_name='迭代次数')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='进度百分比')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('result_ply', models.FileField(blank=True, null=True, upload_to='reconstruction_results/ply/', verbose_name='PLY格式结果')),
                ('result_mesh', models.FileField(blank=True, null=True, upload_to='reconstruction_results/mesh/', verbose_name='网格模型')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='reconstruction_previews/', verbose_name='预览图')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='reconstruction_logs/', verbose_name='日志文件')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '三维重建任务',
                'verbose_name_plural': '三维重建任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/%Y/%m/%d/', verbose_name='上传的图像')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='image_import_module.reconstructiontask', verbose_name='关联的重建任务')),
            ],
            options={
                'verbose_name': '上传的图像',
                'verbose_name_plural': '上传的图像',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
