# Generated by Django 5.2.7 on 2025-12-24 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/%Y/%m/%d/', verbose_name='上传的图像')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '上传的图像',
                'verbose_name_plural': '上传的图像',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
