# Generated by Django 6.0 on 2026-02-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_import_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconstructiontask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态'),
        ),
    ]
